### ISSUE TITLE
Does not work with my ERAsynth (Basic not a + or ++ version)

### ISSUE THREAD

**Issue by Andy1129** [erainstruments/erasynth-firmware#5]
When installing this version the ERAsynth does not work below 30 MHz and gives the wrong frequency, PLL not locked. When using "Low spurious mode" above 30 MHz the ERAsynth is not locked and gives wrong frequency, when entering "Low Phase noise mode" the frequency is correct.

When downgrading to previous version of FW V2, ERAsynth works below and above 30 MHz, but "Low spurious mode"/"Low Phase noise mode" functions are not present.

**Comment by berjk** [comment]
Low phase noise mode does not work under 30MHz. This is mentioned in datasheet. 
https://github.com/erainstruments/erasynth-docs/blob/master/erasynth-datasheet.pdf (Page 21).
But if you go under 30 MHz in low phase noise mode, device can not output correct frequency afterwards. This bug is noted and will be fixed in next release. To be able get correct frequency, set the device above 30 MHz and power cycle.

**Comment by Andy1129** [comment]
Thanks for the quick response!  Looking forward to try the new version of
Firmware!

I have ERAsynth and ERAsynth Micro and they are really  nice products!

Best regards Anders Granström,  CEO TrellCom AB

73 DE SM0IHR

**Comment by berjk** [comment]
This is fixed in the release. Firmware version v1.0.18.
